#Use join funtion to join characters in different ways

L=['a','b','c']               #join funtion=' '.join(L)
a=' '.join(L)
b='-'.join(L)
c=' : : + '.join(L)
d='='.join(L)
e='. &^'.join(L)
f='& &'.join(L)
print(a)
print(b)
print(c)
print(d)
print(e)
print(f)
